version: '3'

services:
    ticketapp:
        image: ticket-app:latest
        ports:
            - "3000:3000"
    ticketapi:
        image: ticket-api:latest
        ports:
            - "3001:3000"