version: '3'

services:
    ticketapp:
        image: ticket-app:latest
        ports:
            - "3000:3000"
    ticketapi:
        image: ticket-api:latest
        depends_on:
            - sqldb
        networks:
            - internalnet
        ports:
            - "3001:3001"
    sqldb:
        image: wayfarer-db:latest
        deploy:
            resources:
                limits:
                    memory: 4G
                reservations:
                    memory: 2G
    #    command: --default-authentication-plugin=mysql_native_password
    #    restart: always
        networks:
            - internalnet
        environment:
            MYSQL_ROOT_PASSWORD: changeme
            constraint: node==node01
        ports:
            - "3306:3306"

networks:
    internalnet:
        driver: overlay
        ipam:
            config:
                - subnet: 192.168.18.0/24