FROM mysql:5

ENV MYSQL_ROOT_PASSWORD=changeme
COPY wayfarerDB/init/ /docker-entrypoint-initdb.d/
COPY .shogun/my.cnf /etc/mysql/my.cnf

EXPOSE 3306

LABEL org.opencontainers.image.source=https://github.com/SamuraiWTF/wayfarer
LABEL org.opencontainers.image.description="Database image wayfarer."
